const types = {
    GET_PRODUCT: 'GET_PRODUCT',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',

    GET_CART: "GET_CART",
    ADD_TO_CART: "ADD_TO_CART",

    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE:'SIGN_UP_FAILURE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export default types;